### Pool pump
- id: pool_pump_on
  alias: "Turn on Pool Pump"
  initial_state: "on"
  trigger:
    platform: sun
    event: sunrise
    offset: '04:00:00'
  action:
    service: homeassistant.turn_on
    entity_id: switch.sw115


- id: pool_pump_off
  alias: "Turn off Pool Pump"
  initial_state: "on"
  trigger:
    platform: state
    entity_id: switch.sw115
    to: "on"
  action:
    service: script.turnpool_off
